# Generated by Django 3.1.3 on 2022-06-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
